language: scala

scala:
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

env:
  global:
    - REPO="user/repo"
    - CI_HOME=`pwd`/$REPO
script: build.sh

# script: travis_retry sbt ++$TRAVIS_SCALA_VERSION clean test
