version: '1'
services:
	server:
		build: target/docker/stage
		ports:
			- "9999:9999"
			- "9990:9990"
		links:
			- client:localhost
		depends_on:
			- client
	client:
		build: target/docker/stage
		ports:
			- "8888:9999"
			- "8880:9990"
		
