/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ServerErrorCause
{
  /// <summary>
  /// Generic server error.
  /// </summary>
  INTERNAL_SERVER_ERROR = 0,
  /// <summary>
  /// Server lacks the ability to fulfill the request.
  /// </summary>
  NOT_IMPLEMENTED = 1,
  /// <summary>
  /// Request cannot be fulfilled due to error from dependent service.
  /// </summary>
  DEPENDENCY_ERROR = 2,
  /// <summary>
  /// Server is currently unavailable.
  /// </summary>
  SERVICE_UNAVAILABLE = 3,
}
